package mvc;

import src.Admin;
import src.Artigo.Artigo;
import src.Artigo.Encomenda;
import src.Utilizador.CompradorVendedor;
import src.Utilizador.Transportador;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Set;

public interface IController {

    IModel getModel();
    IView getView();
    void setModel (IModel model);
    void setView (IView viewer);
    boolean equals(Object o);
    String toString();
    Controller clone();
    void gravarEstado(String filepath) throws FileNotFoundException, IOException;
    void carregarEstado(String filepath) throws FileNotFoundException, IOException, ClassNotFoundException;
    List<Artigo> getArtigosEncomenda(CompradorVendedor compradorVendedor);
    List<Artigo> getArtigosCatalogo();
    void atualizaTransportador(Transportador transportador);
    void atualizaTransportadorPremium(Transportador transportador);
    void atualizaCompradorVendedor(CompradorVendedor compradorVendedor);
    CompradorVendedor getCompradorVendedor(String email, String password);
    Transportador getTransportador(String email, String password);
    Admin getAdmin(String email, String password);
    boolean isValidEmail(String email);
    boolean isValidData1(String data);
    boolean isValidData2(String data);
    boolean igualdade(Artigo a, Artigo b);
    boolean verificaEmail(String email);
    boolean verificaEmailTransportador(String email);
    Encomenda getFinalizaEncomenda(CompradorVendedor compradorVendedor);
    void getProduzFaturaComprador(CompradorVendedor compradorVendedor, Encomenda encomenda);
    void getProduzFaturaVendedor(Encomenda encomenda);
    void getAvancarNoTempo (LocalDate tempoAvancar, CompradorVendedor compradorVendedor);
    void getDevolverEncomenda (CompradorVendedor compradorVendedor, Encomenda encomenda);
    void updateCV(CompradorVendedor compradorVendedor, int quantidade, int opcao);
    void adicionarStockArtigo(Artigo a, int quantidade);
    Artigo getArtigoCompradorVendedor (CompradorVendedor compradorVendedor, int option);
    List<Artigo> getListaDeArtigos();
    void removeArtigo(Artigo artigo);
    void adicionaArtigo(Artigo artigo);
    void removeArtigoCarrinhoCompras (CompradorVendedor compradorVendedor, Artigo artigo);
    void adicionaArtigoProdutosVenda(CompradorVendedor compradorVendedor, Artigo artigo);
    boolean verificaIgualdade(CompradorVendedor compradorVendedor, Artigo artigo);
    void alteraStockArtigo(Artigo artigo, int stockNovo);
    Artigo getArtigoCompradorVendedorCarrinhodeCompras (CompradorVendedor compradorVendedor, int option);
    List<Artigo> getProdutosVenda(CompradorVendedor compradorVendedor);
    LocalDate getTempoDoSistema ();
    void setTempoDoSistema (LocalDate localDate);
    void getAtualizaEncomenda (CompradorVendedor compradorVendedor, Encomenda encomenda);
    CompradorVendedor getVendedorMaiorFaturacaoSempre ();
    CompradorVendedor getVendedorMaiorFaturacaoPeriodoTempo(LocalDate localDate1, LocalDate localDate2);
    Transportador getTransportadorMaiorFaturacaoSempre ();
    List<Artigo> getListaArtigosVendidos (String nome);
    public Set<CompradorVendedor> getMaioresCompradoresSempre ();
    Set<CompradorVendedor> getMaioresCompradoresPeriodoTempo (LocalDate localDate1, LocalDate localDate2);
    Set<CompradorVendedor> getMaioresVendedoresSempre ();
    Set<CompradorVendedor> getMaioresVendedoresPeriodoTempo (LocalDate localDate1, LocalDate localDate2);
    double getLucroVintage();
    List<CompradorVendedor> getListaCompradoresVendedores ();
    Map<String, CompradorVendedor> getListaDeCompradoresVendedores();
    // void addArtigo(Artigo artigo);
    void removeStockArtigoCarrinhoCompras(CompradorVendedor compradorVendedor, int option, int stockManter);
    void removeArtigoCompradorVendedor (CompradorVendedor compradorVendedor, Artigo artigo);
    List<Transportador> getListaDeTransportadores();
    void setListaDeTransportadoresPremium(List<Transportador> listaTransportadoraPremium);
    List<Transportador> getListaDeTransportadoresPremium();
    void adicionaTransportadoraPremium(Transportador t);
    void adicionaTransportadora(Transportador t);
    List<Encomenda> getEncomendasExpedidas (CompradorVendedor compradorVendedor);
    List<Encomenda> getEncomendasFinalizadas (CompradorVendedor compradorVendedor);
    List<String> getListaFaturasComprador (CompradorVendedor compradorVendedor);
    List<String> getListaFaturasVendedor (CompradorVendedor compradorVendedor);
    List<Artigo> getListaArtigosAEntregar (Transportador t);
}