package mvc;

import src.Admin;
import src.Artigo.Artigo;
import src.Artigo.Encomenda;
import src.Utilizador.CompradorVendedor;
import src.Utilizador.Transportador;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Set;

public interface IModel {

    List<Artigo> getListaDeArtigos();
    void setListaDeArtigos(List<Artigo> listaArtigos);
    Map<String, CompradorVendedor> getListaDeCompradoresVendedores();
    void setListaDeCompradoresVendedores(Map<String, CompradorVendedor> listaCompradoresVendedores);
    List<Transportador> getListaDeTransportadores();
    void setListaDeTransportadores(List<Transportador> transportadores);
    List<Transportador> getListaDeTransportadoresPremium();
    void setListaDeTransportadoresPremium(List<Transportador> listaTransportadoraPremium);
    List<Admin> getListaDeAdmins();
    void setListaDeAdmins(List<Admin> listaAdmins);
    double getLucroVintage();
    void setLucroVintage (double lucroVintage);
    LocalDate getTempoSistema();
    void setTempoSistema (LocalDate tempoSistema);
    boolean equals(Object o);
    String toString();
    Model clone();
    void adicionaTransportadoraPremium(Transportador t);
    CompradorVendedor getCompradorVendedor(String email, String password);
    Transportador getTransportador(String email, String password);
    Admin getAdmin(String email, String password);
    List<Artigo> getArtigosEncomenda(CompradorVendedor compradorVendedor);
    List<Encomenda> getEncomendasExpedidas (CompradorVendedor compradorVendedor);
    List<Encomenda> getEncomendasFinalizadas (CompradorVendedor compradorVendedor);
    void removeArtigoCompradorVendedor (CompradorVendedor compradorVendedor, Artigo artigo);
    Artigo getArtigoCompradorVendedor (CompradorVendedor compradorVendedor, int option);
    void updateCV(CompradorVendedor compradorVendedor, int quantidade, int opcao);
    void alteraStockArtigo(Artigo artigo, int stockNovo);
    boolean verificaEmail(String email);
    boolean verificaEmailTransportador(String email);
    void removeArtigo(Artigo artigo);
    void adicionaArtigo(Artigo artigo);
    void adicionaArtigoProdutosVenda(CompradorVendedor compradorVendedor, Artigo artigo);
    boolean verificaIgualdade(CompradorVendedor compradorVendedor, Artigo artigo);
    void removeArtigoCarrinhoCompras (CompradorVendedor compradorVendedor, Artigo artigo);
    Artigo getArtigoCompradorVendedorCarrinhodeCompras (CompradorVendedor compradorVendedor, int option);
    void removeStockArtigoCarrinhoCompras(CompradorVendedor compradorVendedor, int option, int stockManter);
    void atualizaArtigo(Artigo artigo);
    void adicionarStockArtigo(Artigo artigo, int quantidade);
    void adicionaTransportadora(Transportador t);
    void atualizaTransportador(Transportador transportador);
    void atualizaTransportadorPremium(Transportador transportador);
    void atualizaCompradorVendedor(CompradorVendedor compradorVendedor);
    List<Artigo> getProdutosVenda(CompradorVendedor compradorVendedor);
    boolean igualdade(Artigo a, Artigo b);
    Encomenda finalizaEncomenda (CompradorVendedor compradorVendedor);
    void produzFaturaComprador (CompradorVendedor compradorVendedor, Encomenda encomenda);
    void produzFaturaVendedor (Encomenda encomenda);
    void avancarNoTempo (LocalDate tempoAvancar, CompradorVendedor compradorVendedor);
    void devolverEncomenda (CompradorVendedor compradorVendedor, Encomenda encomenda);
    void atualizaEncomenda (CompradorVendedor compradorVendedor, Encomenda encomenda);
    CompradorVendedor vendedorMaiorFaturacaoSempre();
    CompradorVendedor vendedorMaiorFaturacaoPeriodoTempo(LocalDate localDate1, LocalDate localDate2);
    Transportador transportadorMaiorFaturacaoSempre ();
    List<Artigo> listaArtigosVendidos (String nome);
    Set<CompradorVendedor> maioresCompradoresSempre();
    Set<CompradorVendedor> maioresCompradoresPeriodoTempo (LocalDate localDate1, LocalDate localDate2);
    Set<CompradorVendedor> maioresVendedoresSempre();
    Set<CompradorVendedor> maioresVendedoresPeriodoTempo (LocalDate localDate1, LocalDate localDate2);
    void adicionaCompradorVendedor (CompradorVendedor compradorVendedor);
    void adicionaTransportador (Transportador transportador);
    void adicionaAdmin (Admin admin);
    void adicionaArtigo (Artigo artigo, CompradorVendedor compradorVendedor);
    List<String> getListaFaturasCompradorEspecifico(CompradorVendedor compradorVendedor);
    List<String> getListaFaturasVendedorEspecifico(CompradorVendedor compradorVendedor);
    List<Artigo> listaArtigosAEntregar (Transportador t);
}